# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataWorldPlugin
                                 A QGIS plugin
 Load data from dataworld.com
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-01
        copyright            : (C) 2022 by Sergio Costa
        email                : sergio.costa@ufma.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataWorldPlugin class from file DataWorldPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dataworld_plugin import DataWorldPlugin
    return DataWorldPlugin(iface)
