PREFIX amz: <http://purl.org/ontology/dbcells/amazon#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbco: <http://purl.org/ontology/dbcells/cells#>
PREFIX qb: <http://purl.org/linked-data/cube/>
PREFIX lc: <http://purl.org/landchange/amazon/>
PREFIX dbce: <http://www.dbcells.org/epsg4326/>
PREFIX amz: <http://purl.org/ontology/dbcells/amazon> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?id ?wkt ?agric ?forest ?uriCell
WHERE {
    ?id a qb:Observation.
    ?id amz:agric ?agric.
    ?id amz:veg ?forest.
    ?id sdmx:refArea ?uriCell.
    SERVICE <https://dbcells-staging.herokuapp.com/cells> {
        ?uriCell geo:asWKT ?wkt.
    }
}
limit 25